### ISSUE TITLE
Run Setup redux

### ISSUE THREAD

**Issue by davidaray** [ryanlayerlab/TEPEAK#14]
So that this is on the front page, I'm reopening from the closed issue I created several weeks ago.

Thank you for altering the software so it can be used with local data. 

I've been attempting to run the package. I've uploaded a few read pairs and recloned the repository. I also generated all of the necessary files. 

However, I'm running into an error I'm not sure how to deal with. The error is below, as is my config file. 

```
snakemake -s /lustre/work/daray/software/TEPEAK/snakefile --configfile eFus_config.yaml --cores 12
KeyError in file "/lustre/work/daray/software/TEPEAK/snakefile", line 26:
'gene'
  File "/lustre/work/daray/software/TEPEAK/snakefile", line 26, in <module>
```
```
species: eFus
data_dir: data
output_dir: output
zipped_ref_genome_filepath: data/mEptFus1.3.pri.fa.zip
zipped_gtf_filepath: data/eFus_toga.gtf.zip
fastq_input:
  sample_list: eFus_samples.txt
  fastq_dir: data/fastq
input_type: fastq
threads: 8
low: 0
high: 10000
```

The offending line is here:
```
ALL = [
    f'{output_dir}/{species}_global_vcf.txt',
    f'{output_dir}/dfam_annotate.csv',
    f'{output_dir}/{species}_insertions_plot.svg',
    f'{output_dir}/{species}_smoove_plot.svg',
    f'{final}_genes.txt'if config['gene'].lower() in ('y', 'yes') else f'{final}.txt'
]
```

There's no mention of a 'gene' file on the github page unless this is the gtf file. I've checked and rechecked the filename for that gtf and it's correct. 

Thus, I'm at a loss.

**Comment by mrburke00** [comment]
Ah my bad. I didnt handle that config parameter very well. You need to add either `gene: y` or `gene: n` to the config depending on whether you would like annotations. Try that out and let me know. 

Apologies and thank you for your patience testing this. Its just me on this tool so its difficult to catch all the edge cases.

**Comment by mrburke00** [comment]
Ah okay this is actually just an issue with the format of the zip file. When you download the `.gtf` from ncbi it just has a strange internal format that I hardcoded. Let me see if I can replicate this on my end and push a fix.

**Comment by mrburke00** [comment]
@davidaray I pushed what I believe to be a fix. If you run into a similar error send me the log again as well as the output of this 

`unzip -l eFus_toga.gtf.zip | sed -n '1,10p;$p'` - just to see what the unzipped structure ends up looking like, but I believe my fix should be agnostic.

**Comment by davidaray** [comment]
We made it a little farther this time but still not all the way. As requested, the log and the output of the unzip/sed. 

I've done no troubleshooting as of yet but am just pasting this as is. I'll take a look after sending this to see if it's something obvious.

```
Assuming unrestricted shared filesystem usage.
host: cpu-25-56
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 12
Rules claiming more threads will be scaled down.
Job stats:
job                           count
--------------------------  -------
align_species                     1
all                               1
annotate_genes                    1
build_histogram_deletions         1
build_histogram_insertions        1
call_insertions_serial            1
dfam_annotate                     1
extract_range                     1
get_global_vcf                    1
get_species_gtf                   1
process_reference                 1
smoove_1                          4
smoove_2                          1
smoove_3                          4
smoove_4                          1
smoove_global_vcf                 1
write_output_genes                1
total                            23

Select jobs to execute...
Failed to solve scheduling problem with ILP solver, falling back to greedy scheduler. You likely have to fix your ILP solver installation. Error message: PULP_CBC_CMD: Not Available (check permissions on cbc)
Execute 2 jobs...
[Sat Sep 20 11:06:15 2025]
localrule process_reference:
    input: data/mEptFus1.3.pri.fa.zip
    output: data/eFus/eFus.fa, data/eFus/eFus.fa.fai, data/eFus/eFus.fa.amb, data/eFus/eFus.fa.ann, data/eFus/eFus.fa.bwt, data/eFus/eFus.fa.pac, data/eFus/eFus.fa.sa
    jobid: 3
    reason: Missing output files: data/eFus/eFus.fa.amb, data/eFus/eFus.fa.bwt, data/eFus/eFus.fa, data/eFus/eFus.fa.fai, data/eFus/eFus.fa.sa, data/eFus/eFus.fa.pac, data/eFus/eFus.fa.ann
    resources: tmpdir=/tmp
[Sat Sep 20 11:06:15 2025]
localrule get_species_gtf:
    input: data/eFus_toga.gtf.zip
    output: data/eFus/eFus.gtf
    jobid: 21
    reason: Missing output files: data/eFus/eFus.gtf
    resources: tmpdir=/tmp
[Sat Sep 20 11:06:16 2025]
Finished jobid: 21 (Rule: get_species_gtf)
1 of 23 steps (4%) done
RuleException:
CalledProcessError in file "/lustre/work/daray/software/TEPEAK/snakefile", line 82:
Command 'fastq-dump > /dev/null 2>&1 || export PATH=$PATH:$PWD/$(ls | grep "sratoolkit")/bin; /home/daray/miniforge3/envs/insurveyor-env/bin/python3.13 /lustre/scratch/daray/bat1k_TE_analyses/tepeak/.snakemake/scripts/tmpmyp8xd_7.process_reference.py' returned non-zero exit status 1.
[Sat Sep 20 11:06:30 2025]
Error in rule process_reference:
    message: None
    jobid: 3
    input: data/mEptFus1.3.pri.fa.zip
    output: data/eFus/eFus.fa, data/eFus/eFus.fa.fai, data/eFus/eFus.fa.amb, data/eFus/eFus.fa.ann, data/eFus/eFus.fa.bwt, data/eFus/eFus.fa.pac, data/eFus/eFus.fa.sa
Shutting down, this might take some time.
Exiting because a job execution failed. Look below for error messages
[Sat Sep 20 11:06:30 2025]
Error in rule process_reference:
    message: None
    jobid: 3
    input: data/mEptFus1.3.pri.fa.zip
    output: data/eFus/eFus.fa, data/eFus/eFus.fa.fai, data/eFus/eFus.fa.amb, data/eFus/eFus.fa.ann, data/eFus/eFus.fa.bwt, data/eFus/eFus.fa.pac, data/eFus/eFus.fa.sa
Complete log(s): /lustre/scratch/daray/bat1k_TE_analyses/tepeak/.snakemake/log/2025-09-20T110611.033444.snakemake.log
WorkflowError:
At least one job did not complete successfully.
```
```
unzip -l data/eFus_toga.gtf.zip | sed -n '1,10p;$p'
Archive:  data/eFus_toga.gtf.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
250761866  09-18-2025 17:16   eFus_toga.gtf
---------                     -------
250761866                     1 file
250761866                     1 file
```

**Comment by mrburke00** [comment]
Progress! Okay that error code isn't super descriptive but I believe this is a similar error to the gtf zip handling except now for the reference zip. I pushed a fix we'll see if that is the issue. If you see a similar error then run this command for me 

`unzip -l data/mEptFus1.3.pri.fa.zip | sed -n '1,20p;$p'`

**Comment by davidaray** [comment]
Looks like the same error. See paste.
snakemake -s /lustre/work/daray/software/TEPEAK/snakefile --configfile eFus_config.yaml --cores 12
Assuming unrestricted shared filesystem usage.
host: cpu-25-56
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 12
Rules claiming more threads will be scaled down.
Job stats:
job                           count
--------------------------  -------
align_species                     1
all                               1
annotate_genes                    1
build_histogram_deletions         1
build_histogram_insertions        1
call_insertions_serial            1
dfam_annotate                     1
extract_range                     1
get_global_vcf                    1
process_reference                 1
smoove_1                          4
smoove_2                          1
smoove_3                          4
smoove_4                          1
smoove_global_vcf                 1
write_output_genes                1
total                            22

Select jobs to execute...
Execute 1 jobs...

[Sun Sep 21 17:05:16 2025]
localrule process_reference:
    input: data/mEptFus1.3.pri.fa.zip
    output: data/eFus/eFus.fa, data/eFus/eFus.fa.fai, data/eFus/eFus.fa.amb, data/eFus/eFus.fa.ann, data/eFus/eFus.fa.bwt, data/eFus/eFus.fa.pac, data/eFus/eFus.fa.sa
    jobid: 3
    reason: Missing output files: data/eFus/eFus.fa.fai, data/eFus/eFus.fa.amb, data/eFus/eFus.fa.sa, data/eFus/eFus.fa.bwt, data/eFus/eFus.fa.pac, data/eFus/eFus.fa, data/eFus/eFus.fa.ann; Code has changed since last execution
    resources: tmpdir=/tmp
Traceback (most recent call last):
  File "/lustre/scratch/daray/bat1k_TE_analyses/tepeak/.snakemake/scripts/tmp43xqeqo2.process_reference.py", line 64, in <module>
    main()
    ~~~~^^
  File "/lustre/scratch/daray/bat1k_TE_analyses/tepeak/.snakemake/scripts/tmp43xqeqo2.process_reference.py", line 44, in main
    with zipfile.ZipFile(ref_zip) as zf:
                         ^^^^^^^
NameError: name 'ref_zip' is not defined
RuleException:
CalledProcessError in file "/lustre/work/daray/software/TEPEAK/snakefile", line 82:
Command 'fastq-dump > /dev/null 2>&1 || export PATH=$PATH:$PWD/$(ls | grep "sratoolkit")/bin; /home/daray/miniforge3/envs/insurveyor-env/bin/python3.13 /lustre/scratch/daray/bat1k_TE_analyses/tepeak/.snakemake/scripts/tmp43xqeqo2.process_reference.py' returned non-zero exit status 1.
[Sun Sep 21 17:05:17 2025]
Error in rule process_reference:
    message: None
    jobid: 3
    input: data/mEptFus1.3.pri.fa.zip
    output: data/eFus/eFus.fa, data/eFus/eFus.fa.fai, data/eFus/eFus.fa.amb, data/eFus/eFus.fa.ann, data/eFus/eFus.fa.bwt, data/eFus/eFus.fa.pac, data/eFus/eFus.fa.sa
Shutting down, this might take some time.
Exiting because a job execution failed. Look below for error messages
[Sun Sep 21 17:05:17 2025]
Error in rule process_reference:
    message: None
    jobid: 3
    input: data/mEptFus1.3.pri.fa.zip
    output: data/eFus/eFus.fa, data/eFus/eFus.fa.fai, data/eFus/eFus.fa.amb, data/eFus/eFus.fa.ann, data/eFus/eFus.fa.bwt, data/eFus/eFus.fa.pac, data/eFus/eFus.fa.sa
Complete log(s): /lustre/scratch/daray/bat1k_TE_analyses/tepeak/.snakemake/log/2025-09-21T170512.307619.snakemake.log
WorkflowError:
At least one job did not complete successfully.
(insurveyor-env) cpu-25-56:/lustre/scratch/daray/bat1k_TE_analyses/tepeak$ unzip -l data/mEptFus1.3.pri.fa.zip | sed -n '1,20p;$p'
Archive:  data/mEptFus1.3.pri.fa.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
2048219644  09-18-2025 17:18   mEptFus1.3.pri.fa
---------                     -------
2048219644                     1 file
2048219644                     1 file


I appreciate your time on this.

**Comment by davidaray** [comment]
I'm setting this up for a relatively new grad student to run. He's got little experience troubleshooting and we want to get started quickly, so I'm doing the troubleshooting for him. If you're curious, here's the hackmd page I've set up for him to follow and see what it took to get this going. https://hackmd.io/@kazVldy2RCuRgCt5Bnhcgg/r1uQfzUYgg.

**Comment by mrburke00** [comment]
Ah sorry this is just very lazy duplication on my part to get this stood up. Those two different scripts will run depending on the local fastq or NCBI SRA input variable in the config script. See the shell command for the `align_species` rule 
```
 shell:
        """
        if [ "{params.input_type}" = "fastq" ]; then
            echo "Running custom FASTQ alignment..."
            bash -x scripts/align_species.sh \
                -s {params.species} \
                -d {params.species_dir} \
                -t {params.threads} \
                -f {params.fastq_dir} \
                -l {input.sample_file}
        else
            echo "Running SRA alignment..."
            bash src/align_species.sh -s {params.species} -d {params.species_dir} -t {params.threads} -f {input.sample_file}
        fi
        """
```

Did you just end up giving the direct path for `bash -x scripts/align_species.sh`? If so and that works well let me know that's definitely a good edge case for me to implement across the tool. Another weird thing about snakemake just assuming your working directory.

**Comment by davidaray** [comment]
The job was indeed killed for time. The log file is almost exaclty the same length, suggesting that it didn't get any farther despite having been started with --rerun_incomplete.

**Comment by mrburke00** [comment]
Ahh this is actually a change that snakemake has made recently that I overlooked. Give me this weekend to make those changes.

**Comment by davidaray** [comment]
Thank you. I'll come back to this. We're going down for maintenence for 4 days starting tomorrow morning.

**Comment by davidaray** [comment]
I just checked the job and it failed in a similar way:
```
Finished jobid: 4 (Rule: align_species)
2 of 18 steps (11%) done
Select jobs to execute...
Failed to solve scheduling problem with ILP solver, falling back to greedy scheduler. You likely have to fix your ILP solver installation. Error message: PULP_CBC_CMD: Not Available (check permissions on cbc)
Execute 3 jobs...

[Tue Oct 28 16:45:42 2025]
localrule call_insertions_serial:
    input: eFus_samples.txt, data/eFus/eFus.fa, data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam, data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam
    output: output/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14/out.pass.vcf.gz, output/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10/out.pass.vcf.gz
    jobid: 2
    reason: Input files updated by another job: data/eFus/eFus.fa, data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam, data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam
    resources: tmpdir=/tmp
[Tue Oct 28 16:45:42 2025]
localrule smoove_1:
    input: data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam, data/eFus/eFus.fa, data/eFus
    output: output/eFus/results-smoove/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14-smoove.genotyped.vcf.gz
    jobid: 12
    reason: Missing output files: output/eFus/results-smoove/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14-smoove.genotyped.vcf.gz; Input files updated by another job: data/eFus/eFus.fa, data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam
    wildcards: sample=E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14
    resources: tmpdir=/tmp
[Tue Oct 28 16:45:42 2025]
localrule smoove_1:
    input: data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam, data/eFus/eFus.fa, data/eFus
    output: output/eFus/results-smoove/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10-smoove.genotyped.vcf.gz
    jobid: 13
    reason: Missing output files: output/eFus/results-smoove/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10-smoove.genotyped.vcf.gz; Input files updated by another job: data/eFus/eFus.fa, data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam
    wildcards: sample=E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10
    resources: tmpdir=/tmp
/usr/bin/bash: line 1: docker: command not found
/usr/bin/bash: line 1: docker: command not found
RuleException:
CalledProcessError in file "/lustre/work/daray/software/TEPEAK/snakefile", line 264:
Command 'fastq-dump > /dev/null 2>&1 || export PATH=$PATH:$PWD/$(ls | grep "sratoolkit")/bin; mkdir -p output/eFus/results-smoove/ && docker run -v /lustre/scratch/daray/bat1k_TE_analyses/tepeak/data/eFus:/data -v /lustre/scratch/daray/bat1k_TE_analyses/tepeak/output/eFus/results-smoove:/output brentp/smoove smoove call --outdir /output --name E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14 --fasta /data/eFus.fa -p 1 --genotype /data/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam' returned non-zero exit status 127.
[Tue Oct 28 16:45:42 2025]
Error in rule smoove_1:
    message: None
    jobid: 12
    input: data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam, data/eFus/eFus.fa, data/eFus
    output: output/eFus/results-smoove/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14-smoove.genotyped.vcf.gz
    shell:
        mkdir -p output/eFus/results-smoove/ && docker run -v /lustre/scratch/daray/bat1k_TE_analyses/tepeak/data/eFus:/data -v /lustre/scratch/daray/bat1k_TE_analyses/tepeak/output/eFus/results-smoove:/output brentp/smoove smoove call --outdir /output --name E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14 --fasta /data/eFus.fa -p 1 --genotype /data/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam
        (command exited with non-zero exit code)
RuleException:
CalledProcessError in file "/lustre/work/daray/software/TEPEAK/snakefile", line 264:
Command 'fastq-dump > /dev/null 2>&1 || export PATH=$PATH:$PWD/$(ls | grep "sratoolkit")/bin; mkdir -p output/eFus/results-smoove/ && docker run -v /lustre/scratch/daray/bat1k_TE_analyses/tepeak/data/eFus:/data -v /lustre/scratch/daray/bat1k_TE_analyses/tepeak/output/eFus/results-smoove:/output brentp/smoove smoove call --outdir /output --name E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10 --fasta /data/eFus.fa -p 1 --genotype /data/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam' returned non-zero exit status 127.
[Tue Oct 28 16:45:42 2025]
Error in rule smoove_1:
    message: None
    jobid: 13
    input: data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam, data/eFus/eFus.fa, data/eFus
    output: output/eFus/results-smoove/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10-smoove.genotyped.vcf.gz
    shell:
        mkdir -p output/eFus/results-smoove/ && docker run -v /lustre/scratch/daray/bat1k_TE_analyses/tepeak/data/eFus:/data -v /lustre/scratch/daray/bat1k_TE_analyses/tepeak/output/eFus/results-smoove:/output brentp/smoove smoove call --outdir /output --name E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10 --fasta /data/eFus.fa -p 1 --genotype /data/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam
        (command exited with non-zero exit code)
[Tue Oct 28 17:32:33 2025]
Finished jobid: 2 (Rule: call_insertions_serial)
3 of 18 steps (17%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look below for error messages
[Tue Oct 28 17:32:33 2025]
Error in rule smoove_1:
    message: None
    jobid: 12
    input: data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam, data/eFus/eFus.fa, data/eFus
    output: output/eFus/results-smoove/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14-smoove.genotyped.vcf.gz
    shell:
        mkdir -p output/eFus/results-smoove/ && docker run -v /lustre/scratch/daray/bat1k_TE_analyses/tepeak/data/eFus:/data -v /lustre/scratch/daray/bat1k_TE_analyses/tepeak/output/eFus/results-smoove:/output brentp/smoove smoove call --outdir /output --name E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14 --fasta /data/eFus.fa -p 1 --genotype /data/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam
        (command exited with non-zero exit code)
[Tue Oct 28 17:32:33 2025]
Error in rule smoove_1:
    message: None
    jobid: 13
    input: data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam, data/eFus/eFus.fa, data/eFus
    output: output/eFus/results-smoove/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10-smoove.genotyped.vcf.gz
    shell:
        mkdir -p output/eFus/results-smoove/ && docker run -v /lustre/scratch/daray/bat1k_TE_analyses/tepeak/data/eFus:/data -v /lustre/scratch/daray/bat1k_TE_analyses/tepeak/output/eFus/results-smoove:/output brentp/smoove smoove call --outdir /output --name E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10 --fasta /data/eFus.fa -p 1 --genotype /data/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam
        (command exited with non-zero exit code)
Complete log(s): /lustre/scratch/daray/bat1k_TE_analyses/tepeak/.snakemake/log/2025-10-28T124116.303362.snakemake.log
WorkflowError:
At least one job did not complete successfully.
```




In the space below, I paste the history of how I reinstalled and started the job. Maybe I made a mistake somewhere along the way.
```
 2979  cp snakefile /lustre/scratch/daray/bat1k_TE_analyses/tepeak/snakefile.dray
 2980  cd ..
 2981  rm -rf TEPEAK/
 2982  git clone https://github.com/ryanlayerlab/TEPEAK.git
 2983  ls TEPEAK/
 2984  . ~/miniforge3/etc/profile.d/conda.sh
 2985  conda activate insurveyor-env
 2986  which bwa
 2987  cd ~/miniforge3/envs/insurveyor-env/bin/bwa
 2988  cd ~/miniforge3/envs/insurveyor-env/bin/
 2989  wget https://github.com/brentp/smoove/releases/download/v0.2.8/smoove
 2990  chmod +x smoove
 2991  smoove --help
 2992  work
 2993  cd software/TEPEAK/
 2994  cp /lustre/scratch/daray/bat1k_TE_analyses/tepeak/snakefile.dray snakefile
 2995  scratch
 2996  cd bat1k_TE_analyses/tepeak/
 2997  sbatch eFus_tepeak.sh
```
The two command where I moved and replaced the snakefile involve the fact that I hardcoded paths to my TEPEAK directory. 

Any thoughts?

**Comment by mrburke00** [comment]
Alright so I was able to replicate this issue and its something with smoove that I'm going to have to open an issue with on their repo. 

In the meantime I just pushed a new version that adds a flag to the config called `run_smoove` which when set to false will just skip all of the smoove rules. Smoove is just a deletion and duplication SV caller and isn't that critical to the tool nor was it even mentioned in the preprint. So we'll just see if we can get the insertion caller working for you first. 

So pull the new repo, fix the paths, and then add `run_smoove: false` to your config and give it another shot. I was able to get this to run two small samples so fingers crossed.

**Comment by mrburke00** [comment]
I pushed a large amount of changes. Im not sure if they will help fix the core issue yet - I will still need to see the output from above. However you are welcome to try the new code in the meantime just to see - either works for me. I still haven't fixed the global path issue you have to keep fixing so apologies for when you pull the code again. 

There are some additional configuration changes. I believe this is similar to what you have. The new ones at the bottom for dfam - I think thats the species you are working with but feel free to correct anything. 

```
species: eFus
data_dir: data
output_dir: output
zipped_ref_genome_filepath: data/mEptFus1.3.pri.fa.zip
zipped_gtf_filepath: data/eFus_toga.gtf.zip
fastq_input:
  sample_list: eFus_samples.txt
  fastq_dir: data/fastq
input_type: fastq
threads: 64
low: 0
high: 10000
gene: y


#  New TEPEAK Parameters 
tepeak_dfam_organism: "Eptesicus fuscus"  
tepeak_dfam_evalue: 1.0

run_smoove: false
run_enrichment: false 
run_phylogeny: false  
```

**Comment by mrburke00** [comment]
Okay there's some good progress. So looks like there were a few format changes I was not considering in the GTF. I pushed a fix that should work with yours now.

**Comment by mrburke00** [comment]
Hey! Thats awesome. 40th time was the charm haha. Let me know how that full data set goes. I can give some tips if the runtime becomes an issue.

**Comment by davidaray** [comment]
Just an update. Our cluster has a 48 hour wall time and the run made it through the mapping of 22 of he 33 samples submitted using 64 threads, as before.

I've restarted the run to see if it picks up where it left off, in the middle of the 23rd sample. 

We have a second partition that allows for runs up to two weeks but there are fewer processors (36 vs. 128) and lower memory (256 vs. 512) on that second partition.  

I decided to take the advice in the .err file and try a cleanup with this submission script:
```
#!/bin/bash 
#SBATCH --job-name=tepeak
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err
#SBATCH --partition=nocona
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks=128

. ~/miniforge3/etc/profile.d/conda.sh
conda activate insurveyor-env

cd /lustre/scratch/daray/bat1k_TE_analyses/tepeak_large_data

snakemake -s /lustre/work/daray/software/TEPEAK/snakefile --configfile eFus_config.yaml --cleanup-metadata \ data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam \
data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam \
data/eFus/E250036382-L01-NC19_BB_06-E250036382_L01_UDB-6.bam \
data/eFus/E250036382-L01-NC19_BB_100-E250036382_L01_UDB-13.bam \
data/eFus/E250036382-L01-NC19_BB_101-E250036382_L01_UDB-8.bam \
data/eFus/E250036382-L01-NC19_BB_102-E250036382_L01_UDB-1.bam \
data/eFus/E250036382-L01-NC19_BB_109-E250036382_L01_UDB-15.bam \
data/eFus/E250036382-L01-NC19_BB_110-E250036382_L01_UDB-5.bam \
data/eFus/E250036382-L01-NC19_BB_15-E250036382_L01_UDB-18.bam \
data/eFus/E250036382-L01-NC19_BB_16-E250036382_L01_UDB-4.bam \
data/eFus/E250036382-L01-NC19_BB_24-E250036382_L01_UDB-2.bam \
data/eFus/E250036382-L01-NC19_BB_38-E250036382_L01_UDB-7.bam \
data/eFus/E250036382-L01-NC19_BB_43-E250036382_L01_UDB-9.bam \
data/eFus/E250036382-L01-NC19_BB_49-E250036382_L01_UDB-19.bam \
data/eFus/E250036382-L01-NC19_BB_56-E250036382_L01_UDB-16.bam \
data/eFus/E250036382-L01-NC19_BB_57-E250036382_L01_UDB-11.bam \
data/eFus/E250036382-L01-NC19_BB_69-E250036382_L01_UDB-12.bam \
data/eFus/E250036382-L01-NC19_BB_70-E250036382_L01_UDB-3.bam \
data/eFus/E250036382-L01-NC19_BB_87-E250036382_L01_UDB-20.bam \
data/eFus/E250036382-L01-NC19_BB_9-E250036382_L01_UDB-17.bam \
data/eFus/NC19_014_TATCCAGT-TGAGCTAC_S177_L004.bam \
data/eFus/NC19_029_GCATAGCC-TGGTTCCT_S178_L004.bam \
data/eFus/NC19_BB-PIOTR_8_CTAACCTCAA-TCACAGTTGC_S1_L004.bam \
data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam.bai \
data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam.bai \
data/eFus/E250036382-L01-NC19_BB_06-E250036382_L01_UDB-6.bam.bai \
data/eFus/E250036382-L01-NC19_BB_100-E250036382_L01_UDB-13.bam.bai \
data/eFus/E250036382-L01-NC19_BB_101-E250036382_L01_UDB-8.bam.bai \
data/eFus/E250036382-L01-NC19_BB_102-E250036382_L01_UDB-1.bam.bai \
data/eFus/E250036382-L01-NC19_BB_109-E250036382_L01_UDB-15.bam.bai \
data/eFus/E250036382-L01-NC19_BB_110-E250036382_L01_UDB-5.bam.bai \
data/eFus/E250036382-L01-NC19_BB_15-E250036382_L01_UDB-18.bam.bai \
data/eFus/E250036382-L01-NC19_BB_16-E250036382_L01_UDB-4.bam.bai \
data/eFus/E250036382-L01-NC19_BB_24-E250036382_L01_UDB-2.bam.bai \
data/eFus/E250036382-L01-NC19_BB_38-E250036382_L01_UDB-7.bam.bai \
data/eFus/E250036382-L01-NC19_BB_43-E250036382_L01_UDB-9.bam.bai \
data/eFus/E250036382-L01-NC19_BB_49-E250036382_L01_UDB-19.bam.bai \
data/eFus/E250036382-L01-NC19_BB_56-E250036382_L01_UDB-16.bam.bai \
data/eFus/E250036382-L01-NC19_BB_57-E250036382_L01_UDB-11.bam.bai \
data/eFus/E250036382-L01-NC19_BB_69-E250036382_L01_UDB-12.bam.bai \
data/eFus/E250036382-L01-NC19_BB_70-E250036382_L01_UDB-3.bam.bai \
data/eFus/E250036382-L01-NC19_BB_87-E250036382_L01_UDB-20.bam.bai \
data/eFus/E250036382-L01-NC19_BB_9-E250036382_L01_UDB-17.bam.bai \
data/eFus/NC19_014_TATCCAGT-TGAGCTAC_S177_L004.bam.bai \
data/eFus/NC19_029_GCATAGCC-TGGTTCCT_S178_L004.bam.bai \
data/eFus/NC19_BB-PIOTR_8_CTAACCTCAA-TCACAGTTGC_S1_L004.bam.bai \


snakemake -s /lustre/work/daray/software/TEPEAK/snakefile \
	--configfile eFus_config.yaml \
	--cores 128 \
	--rerun-incomplete
```
Unfortunately, that failed, probably because I didn't do something correctly. 
```
Error while loading conda entry point: conda-libmamba-solver (cannot import name 'Spinner' from 'conda.common.io' (/home/daray/miniforge3/lib/python3.12/site-packages/conda/common/io.py))
WorkflowError:
Failed to clean up metadata for the following files because the metadata was not present.
If this is expected, there is nothing to do.
Otherwise, the reason might be file system latency or still running jobs.
Consider running metadata cleanup again.
Files:
data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam
data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam
data/eFus/E250036382-L01-NC19_BB_06-E250036382_L01_UDB-6.bam
data/eFus/E250036382-L01-NC19_BB_100-E250036382_L01_UDB-13.bam
data/eFus/E250036382-L01-NC19_BB_101-E250036382_L01_UDB-8.bam
data/eFus/E250036382-L01-NC19_BB_102-E250036382_L01_UDB-1.bam
data/eFus/E250036382-L01-NC19_BB_109-E250036382_L01_UDB-15.bam
data/eFus/E250036382-L01-NC19_BB_110-E250036382_L01_UDB-5.bam
data/eFus/E250036382-L01-NC19_BB_15-E250036382_L01_UDB-18.bam
data/eFus/E250036382-L01-NC19_BB_16-E250036382_L01_UDB-4.bam
data/eFus/E250036382-L01-NC19_BB_24-E250036382_L01_UDB-2.bam
data/eFus/E250036382-L01-NC19_BB_38-E250036382_L01_UDB-7.bam
data/eFus/E250036382-L01-NC19_BB_43-E250036382_L01_UDB-9.bam
data/eFus/E250036382-L01-NC19_BB_49-E250036382_L01_UDB-19.bam
data/eFus/E250036382-L01-NC19_BB_56-E250036382_L01_UDB-16.bam
data/eFus/E250036382-L01-NC19_BB_57-E250036382_L01_UDB-11.bam
data/eFus/E250036382-L01-NC19_BB_69-E250036382_L01_UDB-12.bam
data/eFus/E250036382-L01-NC19_BB_70-E250036382_L01_UDB-3.bam
data/eFus/E250036382-L01-NC19_BB_87-E250036382_L01_UDB-20.bam
data/eFus/E250036382-L01-NC19_BB_9-E250036382_L01_UDB-17.bam
data/eFus/NC19_014_TATCCAGT-TGAGCTAC_S177_L004.bam
data/eFus/NC19_029_GCATAGCC-TGGTTCCT_S178_L004.bam
data/eFus/NC19_BB-PIOTR_8_CTAACCTCAA-TCACAGTTGC_S1_L004.bam
data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam.bai
data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam.bai
data/eFus/E250036382-L01-NC19_BB_06-E250036382_L01_UDB-6.bam.bai
data/eFus/E250036382-L01-NC19_BB_100-E250036382_L01_UDB-13.bam.bai
data/eFus/E250036382-L01-NC19_BB_101-E250036382_L01_UDB-8.bam.bai
data/eFus/E250036382-L01-NC19_BB_102-E250036382_L01_UDB-1.bam.bai
data/eFus/E250036382-L01-NC19_BB_109-E250036382_L01_UDB-15.bam.bai
data/eFus/E250036382-L01-NC19_BB_110-E250036382_L01_UDB-5.bam.bai
data/eFus/E250036382-L01-NC19_BB_15-E250036382_L01_UDB-18.bam.bai
data/eFus/E250036382-L01-NC19_BB_16-E250036382_L01_UDB-4.bam.bai
data/eFus/E250036382-L01-NC19_BB_24-E250036382_L01_UDB-2.bam.bai
data/eFus/E250036382-L01-NC19_BB_38-E250036382_L01_UDB-7.bam.bai
data/eFus/E250036382-L01-NC19_BB_43-E250036382_L01_UDB-9.bam.bai
data/eFus/E250036382-L01-NC19_BB_49-E250036382_L01_UDB-19.bam.bai
data/eFus/E250036382-L01-NC19_BB_56-E250036382_L01_UDB-16.bam.bai
data/eFus/E250036382-L01-NC19_BB_57-E250036382_L01_UDB-11.bam.bai
data/eFus/E250036382-L01-NC19_BB_69-E250036382_L01_UDB-12.bam.bai
data/eFus/E250036382-L01-NC19_BB_70-E250036382_L01_UDB-3.bam.bai
data/eFus/E250036382-L01-NC19_BB_87-E250036382_L01_UDB-20.bam.bai
data/eFus/E250036382-L01-NC19_BB_9-E250036382_L01_UDB-17.bam.bai
data/eFus/NC19_014_TATCCAGT-TGAGCTAC_S177_L004.bam.bai
data/eFus/NC19_029_GCATAGCC-TGGTTCCT_S178_L004.bam.bai
data/eFus/NC19_BB-PIOTR_8_CTAACCTCAA-TCACAGTTGC_S1_L004.bam.bai
Assuming unrestricted shared filesystem usage.
host: cpu-23-21
Building DAG of jobs...
LockException:
Error: Directory cannot be locked. Please make sure that no other Snakemake process is trying to create the same files in the following directory:
/lustre/scratch/daray/bat1k_TE_analyses/tepeak_large_data
If you are sure that no other instances of snakemake are running on this directory, the remaining lock was likely caused by a kill signal or a power loss. It can be removed with the --unlock argument.
```

**Comment by mrburke00** [comment]
Okay so looks like it is not running in parallel. I think I pushed a fix if you want to pull again. Before you try a full run try adding the `--dry-run` command like below. It will basically show you what will get executed without doing it. What I am looking for is a change from one job for align and call insertions to the number of samples you are running. So for my two samples it would look like below. This change is most likely going to retrigger the entire pipeline so if you want to try it with just two samples again just to make sure it runs through. Up to you. 


```
TEPEAK % snakemake --configfile config_horse.yaml --cores 8 --dry-run
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job stats:
job                           count
--------------------------  -------
align_one_sample                  2
call_insertions_one_sample        2
total                             4
```

**Comment by davidaray** [comment]
Updates. The dry run seemes to have worked. I see no errors in the output files.

So, then I tried a real run with the same two samples that worked previously and hit a problem.

This time, even I can see what the issue is. All the mapping completes but when the package starts the merging step with picard tools, there's a path error.
```
[main] Version: 0.7.18-r1243-dirty
[main] CMD: bwa mem -M -t 32 -R @RG\tID:E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10\tSM:E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10 data/eFus/eFus.fa /tmp/tmp.vzo1UIYEmE/r1.fq /tmp/tmp.vzo1UIYEmE/r2.fq
[main] Real time: 8834.291 sec; CPU: 273164.511 sec
[bam_sort_core] merging from 10 files and 32 in-memory blocks...
samtools: /home/daray/miniforge3/envs/insurveyor-env/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /home/daray/miniforge3/envs/insurveyor-env/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /home/daray/miniforge3/envs/insurveyor-env/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /home/daray/miniforge3/envs/insurveyor-env/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /home/daray/miniforge3/envs/insurveyor-env/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /home/daray/miniforge3/envs/insurveyor-env/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /home/daray/miniforge3/envs/insurveyor-env/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /home/daray/miniforge3/envs/insurveyor-env/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
Error: Unable to access jarfile /lustre/work/daray/software/TEPEAK/scripts/../picard/build/libs/picard.jar
samtools: /home/daray/miniforge3/envs/insurveyor-env/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /home/daray/miniforge3/envs/insurveyor-env/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /home/daray/miniforge3/envs/insurveyor-env/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /home/daray/miniforge3/envs/insurveyor-env/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
[E::hts_open_format] Failed to open file "data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.rg.bam" : No such file or directory
samtools index: failed to open "data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.rg.bam": No such file or directory
mv: cannot stat 'data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.rg.bam': No such file or directory

and so on...
```
You can see there in the middle that it's looking in the wrong place for picard.jar. 

That's something I can usually fix by coding the path but I'm not sure where the call for picard.jar is coming from. There's nothing in the snakefile that asks for it so it must be from one of the scripts the snakefile calls. 

Could you tell me which one to modify?

**Comment by davidaray** [comment]
I found the two offending scripts. It's the three align_species.sh versions.

I hardcoded the path to my picard installation and am rerunning to see if it makes it through this time.

**Comment by mrburke00** [comment]
Oh geez Im sorry I was apparently very much not paying attention when I merged branches. Let me know if the picard path worked and I can clean up these files for you.

**Comment by mrburke00** [comment]
Hmm thats strange. I'll dig into this one. 

I ran the pipeline last night and ran into an issue downstream so I'll see if I can push a fix for both this and that this evening.

**Comment by mrburke00** [comment]
Alright so this is an issue with Picard just running out of storage on your machine. 

Just to recap we are trying to get the alignment rule to execute in parallel which we can see is now working with this: 

```
[Tue Nov 18 15:50:32 2025]
rule align_one_sample:
    input: data/eFus/eFus.fa, data/eFus/eFus.fa.fai, data/eFus/eFus.fa.amb, data/eFus/eFus.fa.ann, data/eFus/eFus.fa.bwt, data/eFus/eFus.fa.pac, data/eFus/eFus.fa.sa, eFus_samples.txt
    output: data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam, data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam.bai
    jobid: 4
    reason: Missing output files: data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam
    wildcards: sample=E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14
    threads: 32
    resources: tmpdir=/tmp


[Tue Nov 18 15:50:32 2025]
rule align_one_sample:
    input: data/eFus/eFus.fa, data/eFus/eFus.fa.fai, data/eFus/eFus.fa.amb, data/eFus/eFus.fa.ann, data/eFus/eFus.fa.bwt, data/eFus/eFus.fa.pac, data/eFus/eFus.fa.sa, eFus_samples.txt
    output: data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam, data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam.bai
    jobid: 5
    reason: Missing output files: data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam
    wildcards: sample=E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10
    threads: 32
    resources: tmpdir=/tmp

```

The problem is these two jobs have no awareness of each other hence they soak up all the storage and crash. I really only have one idea for how to fix this if that doesn't work I will just make you a separate fork that splits the pipeline to two phases so that you can run your full dataset easier at the cost of just being a bit more hands on with your configs. 

I pushed the fix for what may work. Fingers crossed.

**Comment by davidaray** [comment]
The latest:

```
[BWTIncConstructFromPacked] 460 iterations done. 3996140292 characters processed.
[BWTIncConstructFromPacked] 470 iterations done. 4016115732 characters processed.
[bwt_gen] Finished constructing BWT in 470 iterations.
[bwa_index] 1184.37 seconds elapse.
[bwa_index] Update BWT... 7.83 sec
[bwa_index] Pack forward-only FASTA... 7.21 sec
[bwa_index] Construct SA from BWT and Occ... 490.87 sec
[main] Version: 0.7.19-r1273
[main] CMD: bwa index -p data/eFus/eFus.fa data/eFus/eFus.fa
[main] Real time: 1716.129 sec; CPU: 1701.121 sec
[Tue Nov 25 17:03:50 2025]
Finished job 3.
2 of 12 steps (17%) done
Select jobs to execute...

[Tue Nov 25 17:03:50 2025]
rule align_one_sample:
    input: data/eFus/eFus.fa, data/eFus/eFus.fa.fai, data/eFus/eFus.fa.amb, data/eFus/eFus.fa.ann, data/eFus/eFus.fa.bwt, data/eFus/eFus.fa.pac, data/eFus/eFus.fa.sa, eFus_samples.txt
    output: data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam, data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam.bai
    jobid: 4
    reason: Missing output files: data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam; Input files updated by another job: data/eFus/eFus.fa.fai, data/eFus/eFus.fa, data/eFus/eFus.fa.amb, data/eFus/eFus.fa.ann, data/eFus/eFus.fa.bwt, data/eFus/eFus.fa.sa, data/eFus/eFus.fa.pac
    wildcards: sample=E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14
    threads: 32
    resources: tmpdir=/tmp


[Tue Nov 25 17:03:50 2025]
rule align_one_sample:
    input: data/eFus/eFus.fa, data/eFus/eFus.fa.fai, data/eFus/eFus.fa.amb, data/eFus/eFus.fa.ann, data/eFus/eFus.fa.bwt, data/eFus/eFus.fa.pac, data/eFus/eFus.fa.sa, eFus_samples.txt
    output: data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam, data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam.bai
    jobid: 5
    reason: Missing output files: data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam; Input files updated by another job: data/eFus/eFus.fa.fai, data/eFus/eFus.fa, data/eFus/eFus.fa.amb, data/eFus/eFus.fa.ann, data/eFus/eFus.fa.bwt, data/eFus/eFus.fa.sa, data/eFus/eFus.fa.pac
    wildcards: sample=E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10
    threads: 32
    resources: tmpdir=/tmp

Waiting at most 5 seconds for missing files.
MissingOutputException in rule align_one_sample in file /lustre/work/daray/software/TEPEAK/snakefile, line 111:
Job 5  completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam
data/eFus/E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10.bam.bai
Waiting at most 5 seconds for missing files.
MissingOutputException in rule align_one_sample in file /lustre/work/daray/software/TEPEAK/snakefile, line 111:
Job 4  completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam
data/eFus/E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14.bam.bai
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2025-11-25T163432.296920.snakemake.log
```

**Comment by mrburke00** [comment]
Okay I pushed a fix. Looks to me like just a path issue. I also attempted a fix so you don't have to hardcode this `/lustre/work/daray/software/TEPEAK/src/align_species_fastq.sh`. Its now an absolute path at Line 124 in Snakefile_stage1.py `SCRIPT_PATH="$PWD/scripts/align_species.sh"`. 

Sorry about the picard issue if you want to send what your additional location was I can add that to the list of locations snakemake attempts to look for. 

Try pulling the new version and running again.

**Comment by davidaray** [comment]
Good news. The run with four samples in two stages worked. I got the expected output files. Just started a run with 33 samples in two batches and we'll see how it goes.

**Comment by mrburke00** [comment]
Excellent! Depending on your execution times and cluster time restrictions you can split the 33 samples into as many batches as you need.

**Comment by davidaray** [comment]
We're close. So close.  I ran two tests. The first involved two batches as described above, 16 samples in one back and 17 in another. The second test broke the same samples into 6 batches of 6, 6, 7, 5, 6, and 3.  

The issue is going to be one of wall time. Our HPCC director doesn't understand genomics and refuses to accept that some jobs need to run longer than 48 hours. 

Thus, the first test was killed upon reaching the 48 hour time limit and the second is very close to reaching that limit and is unlikely to finish in time.

```
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 4238412 reads in 2839.683 CPU sec, 45.246 real sec
slurmstepd: error: *** JOB 22820764 ON cpu-23-8 CANCELLED AT 2025-12-22T08:06:36 DUE TO TIME LIMIT ***
```

This makes me wonder if the Stage1 is being run in parallel or in series. If it's in series, running more samples will always hit the time problem on our HPCC. If they're running parallel, this shouldn't be an issue. 

My current Stage1 implementation is:
```
for ((CHUNKNUMBER=1; CHUNKNUMBER<=n; CHUNKNUMBER++)); do
    echo "Processing chunk_0${CHUNKNUMBER}..."
#    cp "$chunk" your_species_samples.txt   # this .txt is the one referenced as sample_list in the config
    sed "s/eFus_samples.txt/eFus_chunk_0${CHUNKNUMBER}.txt/g" eFus_config.yaml >eFus_config_0${CHUNKNUMBER}.yaml
	snakemake -s /lustre/work/daray/software/TEPEAK/Snakefile_stage1.py --configfile eFus_config_0${CHUNKNUMBER}.yaml --cores 128 
done
```
I don't use snakemake a lot so I can't determine if the stage1 jobs are in parallel or in series.

Assuming they're in series, is it possible to run multiple instances of Stage1 simultaneously. I've used other packages that employ snakemake (https://github.com/DrosophilaGenomeEvolution/TrEMOLO/issues/28) and ran into an issue where snakemake stepped on its own toes when trying to run parallel jobs.

Their response - "Indeed, the pipeline generates a Snakefile that it subsequently calls. If the pipeline is run in parallel from the same directory, conflicts can occur. We can fix this issue by appending a suffix to the Snakefile based on the current time in nanoseconds to avoid duplicates. File writing tasks are slow enough for this solution to be effective. Once the issue is resolved, we will get back to you."

They did exactly as promised and it runs fine now.

I'm going to attempt a set of parallel runs by modifying the implementation I'm currently using and see if I run into the same issue. 

Thoughts?

**Comment by mrburke00** [comment]
Ah okay so if Im reading your snippet correctly it looks like youre submitting all of the batches into the same slurm script. What I had in mind was more along the lines of

```
for ((CHUNKNUMBER=1; CHUNKNUMBER<=6; CHUNKNUMBER++)); do
    sbatch --job-name="tepeak_chunk_${CHUNKNUMBER}" \
           --time=48:00:00 \
           --cpus-per-task=32 \
           --wrap="snakemake -s Snakefile_stage1.py --configfile eFus_config_0${CHUNKNUMBER}.yaml --cores 32"
done
```
so each chunk/batch gets submitted to a different slurm execution. Then you can likely use less cores for running the smaller set of samples or whatever works. But in your case you'd get 6 different slurm jobs put in queue simultaneously.

The challenging part of running a bunch of these in parallel within a single slurm script is snakemake really struggles to control the memory of each of those parallel executions. You can definitely give that parallel idea a shot and see I don't have any experience with that package. 

Sorry for the confusion. Let me know if you need me to explain anything further.

**Comment by davidaray** [comment]
Yeah. I can see that.

I ended up with something like this:
```
#!/bin/bash 
#SBATCH --job-name=tepeak
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err
#SBATCH --partition=nocona
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks=1

WORKDIR=/lustre/scratch/daray/bat1k_TE_analyses/tepeak_large_data
TEPEAK=/lustre/work/daray/software/TEPEAK

cd $WORKDIR

n=$(wc -l < chunks.txt)

for ((CHUNKNUMBER=1; CHUNKNUMBER<=n; CHUNKNUMBER++)); do
    CHUNK=$(printf "%02d" "$CHUNKNUMBER")

    JOBSCRIPT="eFus_stage1_${CHUNK}.sh"
    CONFIG="eFus_config_${CHUNK}.yaml"

    echo "Generating and submitting ${JOBSCRIPT}"

    # Create chunk-specific config
    sed "s/eFus_samples.txt/eFus_chunk_${CHUNK}.txt/g" \
        eFus_config.yaml > "${CONFIG}"

    # Generate SLURM script
    cat > "${JOBSCRIPT}" <<EOF
#!/usr/bin/env bash
#SBATCH --job-name=eFus_${CHUNK}
#SBATCH --output=eFus_${CHUNK}.%j.out
#SBATCH --error=eFus_${CHUNK}.%j.err
#SBATCH --partition=nocona
#SBATCH --time=48:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=128

set -euo pipefail

. ~/miniforge3/etc/profile.d/conda.sh
conda activate insurveyor-env

echo "Running chunk ${CHUNK} on \$(hostname)"

cd ${WORKDIR}

snakemake \\
	-s ${TEPEAK}/snakefile \\
	--configfile eFus_config.yaml \\
	--unlock

snakemake \\
    -s ${TEPEAK}/Snakefile_stage1.py \\
    --configfile ${CONFIG} \\
    --cores 128
EOF

    sbatch "${JOBSCRIPT}"
done
```
It does what I think may be essentially the same thing. 

Running now.

**Comment by mrburke00** [comment]
Yeah that looks right to me.

**Comment by davidaray** [comment]
Great news. 

```
============================================================
TEPEAK: SAVING RESULTS
============================================================

Saved 356 families to output/eFus/tepeak_families_annotated.csv

Successfully annotated: 328/356 families
Total insertions annotated: 609,129
Stage 2: Auto-detected 33 completed samples from VCF files
Detected samples: E250036382-L01-NC19_BB_02-E250036382_L01_UDB-14, E250036382-L01-NC19_BB_04-E250036382_L01_UDB-10, E250036382-L01-NC19_BB_06-E250036382_L01_UDB-6, E250036382-L01-NC19_BB_100-E250036382_L01_UDB-13, E250036382-L01-NC19_BB_101-E250036382_L01_UDB-8, E250036382-L01-NC19_BB_102-E250036382_L01_UDB-1, E250036382-L01-NC19_BB_109-E250036382_L01_UDB-15, E250036382-L01-NC19_BB_110-E250036382_L01_UDB-5, E250036382-L01-NC19_BB_15-E250036382_L01_UDB-18, E250036382-L01-NC19_BB_16-E250036382_L01_UDB-4...

```

Our next test will be for the entire 100+ sample data set.

I really appreciate your tireless help in getting this to work.

**Comment by mrburke00** [comment]
Excellent news! Those look like some very decent initial metrics as well. 

Look forward to hearing how the big run goes. 

No worries at all. I appreciate your patience in helping me getting this in running shape.

**Comment by davidaray** [comment]
Final update. It worked great except for two samples. They gave me significant problems and I'm not sure why. They don't appear to be any different from any of the other samples but I'm not going to worrry about it now. 

Running everything for stage 1 had to be done in batches ranging from 4-10 samples/ per run. Occasionally needed to restart the analyses with the restart option. 

Stage 2 went smoothly and finished in under a day for all ~100 samples. 

Thank you again for all the help getting it to work. I'm currently recommending this package to a colleague working on tick genomics.

**Comment by mrburke00** [comment]
Thats great news. Yeah Ive come across a few rare samples that won't process. Ive never been able to replicate the issue reliably so if you ever learn of anything that I can help with definitely reach out. 

I really appreciate your patience in sticking with this. Longest github issue ever haha! 

Thanks for the recommendation. I passed your info along to my PI, Ryan Layer (ryan.layer@colorado.edu), he may have reached out already - if there's any interest in broader collaboration.

**Comment by davidaray** [comment]
A quick update for your information. The pipeline has been running very well but I had one issue. Some jobs were getting stuck on the final step, 'call_insertions_one_sample'. This is partially our own problem.

Our HPCC director refuses to let anything run longer than 48 hours. He's not a genomics person and simply refuses to accept that long jobs are a real thing.

Because of that, this last step was sometimes taking longer than the alotted 48 hours. We imply changed the threads from '1' to '64' on line 193. That solved the problem.

It might be worth changing that in the repository.
